// GET_RECOMMENDED_STATION //
export const GET_RECOMMENDED_STATION_REQUEST = 'GET_RECOMMENDED_STATION_REQUEST'
export const GET_RECOMMENDED_STATION_SUCCESS = 'GET_RECOMMENDED_STATION_SUCCESS'
export const GET_RECOMMENDED_STATION_FAILED = 'GET_RECOMMENDED_STATION_FAILED'