// GET_RECOMMENDED_STATION //
export const GET_RECOMMENDED_STATION_REQUEST = 'GET_RECOMMENDED_STATION_REQUEST'
export const GET_RECOMMENDED_STATION_SUCCESS = 'GET_RECOMMENDED_STATION_SUCCESS'
export const GET_RECOMMENDED_STATION_FAILED = 'GET_RECOMMENDED_STATION_FAILED'

// GET_SEARCHED_TERM //
export const GET_SEARCHED_TERM_REQUEST = 'GET_SEARCHED_TERM_REQUEST'
export const GET_SEARCHED_TERM_SUCCESS = 'GET_SEARCHED_TERM_SUCCESS'
export const GET_SEARCHED_TERM_FAILED = 'GET_SEARCHED_TERM_FAILED'